In [1]:
import numpy as np
import pandas as pd

In [2]:
#numpy version
np.__version__

'1.21.2'

In [3]:
#pandas version
pd.__version__

'1.3.3'

In [4]:
data = pd.read_csv('data.csv.txt')
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
#Question 3
#What's the average price of BMW cars in the dataset?
bmw = data[data['Make'] == 'BMW']
bmw['MSRP'].sum()/len(bmw['MSRP'])

61546.76347305389

In [6]:
bmw['MSRP'].mean()

61546.76347305389

In [7]:
#Question 4
#Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after).
#How many of them have missing values for Engine HP?

after2015 = data[data['Year'] >= 2015]
after2015['Engine HP'].isnull().sum()


51

In [8]:
#Question 5
#Calculate the average "Engine HP" in the dataset.
#Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
#Now, calcualte the average of "Engine HP" again.
#Has it changed? NO
df = data.copy()

avgHP = df['Engine HP'].mean()
avgHP

249.38607007176023

In [9]:
df['Engine HP'] = df['Engine HP'].fillna(avgHP)

In [10]:
navgHP = df['Engine HP'].mean()
navgHP

249.38607007176023

In [12]:
data['Engine HP'].fillna(0).mean() #fill with zero changes the mean 

247.94174920261878

In [24]:
rr = data[data['Make'] == "Rolls-Royce"]
rr = rr[["Engine HP", "Engine Cylinders", "highway MPG"]]
rr.drop_duplicates(inplace = True)
X = rr.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [25]:
XT = X.T
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [30]:
XTX = XT.dot(X) #the order here matters 
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [31]:
#invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv.sum()

0.032212320677486125

In [34]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

XTX_inv.dot(XT).dot(y)[0]

0.19989598183188972